export const mockInternships = [
  {
    id: 1,
    title: "Software Engineering Intern",
    company: {
      id: 101,
      companyName: "TechGiant Co.",
      logo: "https://placehold.co/100x100?text=TG",
      location: "Cairo, Egypt",
      industry: "Technology"
    },
    description: "Join our engineering team to develop cutting-edge web applications. You'll work with React, Node.js, and our cloud infrastructure to build scalable solutions for our enterprise customers.",
    requirements: [
      "Currently pursuing a degree in Computer Science or related field",
      "Familiarity with JavaScript and modern web frameworks",
      "Basic understanding of data structures and algorithms",
      "Strong problem-solving skills"
    ],
    location: "Cairo, Egypt",
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    durationMonths: 3,
    paid: true,
    salary: 4000,
    skills: ["JavaScript", "React", "Node.js", "Cloud", "Data Structures", "Algorithms"],
    industry: "Technology",
    isApproved: true,
    applicationsCount: 15,
    isRemote: false,
    department: "Engineering",
    contactPerson: "Ahmed Hassan",
    tags: ["Software Development", "Web", "Frontend", "Backend"],
    createdAt: "2025-01-10T10:00:00Z"
  },
  {
    id: 2,
    title: "Data Science Intern",
    company: {
      id: 102,
      companyName: "DataMetrics",
      logo: "https://placehold.co/100x100?text=DM",
      location: "Alexandria, Egypt",
      industry: "Technology"
    },
    description: "Help us analyze large datasets and build predictive models. You'll work with our data science team to extract meaningful insights using Python, pandas, and scikit-learn.",
    requirements: [
      "Currently pursuing a degree in Computer Science, Statistics, or related field",
      "Experience with Python and data analysis libraries",
      "Knowledge of statistical methods",
      "Ability to communicate complex findings clearly"
    ],
    location: "Alexandria, Egypt",
    startDate: "2025-06-15",
    endDate: "2025-09-15",
    durationMonths: 3,
    paid: true,
    salary: 3500,
    skills: ["Python", "Data Analysis", "Statistics", "Machine Learning"],
    industry: "Technology",
    isApproved: true,
    applicationsCount: 8,
    isRemote: false,
    department: "Data Science",
    contactPerson: "Sara Mahmoud",
    tags: ["Data Science", "Machine Learning", "Python", "Analytics"],
    createdAt: "2025-01-15T09:30:00Z"
  },
  {
    id: 3,
    title: "UX/UI Design Intern",
    company: {
      id: 103,
      companyName: "DesignWorks",
      logo: "https://placehold.co/100x100?text=DW",
      location: "Giza, Egypt",
      industry: "Design"
    },
    description: "Join our creative team to design beautiful and functional user interfaces. You'll contribute to the design process from ideation to final implementation.",
    requirements: [
      "Studying design, HCI, or related field",
      "Proficiency with design tools like Figma or Adobe XD",
      "Understanding of UI/UX principles",
      "Portfolio demonstrating creative abilities"
    ],
    location: "Giza, Egypt",
    startDate: "2025-06-01",
    endDate: "2025-08-15",
    durationMonths: 2.5,
    paid: true,
    salary: 3000,
    skills: ["Figma", "Adobe XD", "UI/UX", "Design Principles"],
    industry: "Design",
    isApproved: true,
    applicationsCount: 12,
    isRemote: false,
    department: "Design",
    contactPerson: "Laila Hamed",
    tags: ["Design", "UI/UX", "Figma", "Creative"],
    createdAt: "2025-01-20T14:15:00Z"
  },
  {
    id: 4,
    title: "Mobile App Development Intern",
    company: {
      id: 101,
      companyName: "TechGiant Co.",
      logo: "https://placehold.co/100x100?text=TG",
      location: "Cairo, Egypt",
      industry: "Technology"
    },
    description: "Work on our mobile applications for iOS and Android platforms using React Native. You'll gain hands-on experience with modern mobile development practices.",
    requirements: [
      "Computer Science or Software Engineering student",
      "Knowledge of JavaScript and React basics",
      "Interest in mobile development",
      "Problem-solving mindset"
    ],
    location: "Cairo, Egypt",
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    durationMonths: 3,
    paid: true,
    salary: 3500,
    skills: ["JavaScript", "React Native", "Mobile Development"],
    industry: "Technology",
    isApproved: false,
    applicationsCount: 0,
    isRemote: true,
    department: "Mobile Development",
    contactPerson: "Mohamed Salah",
    tags: ["Mobile", "React Native", "JavaScript", "App Development"],
    createdAt: "2025-01-25T11:45:00Z"
  },
  {
    id: 5,
    title: "Digital Marketing Intern",
    company: {
      id: 104,
      companyName: "MarketBoost",
      logo: "https://placehold.co/100x100?text=MB",
      location: "Cairo, Egypt",
      industry: "Marketing"
    },
    description: "Join our marketing team to learn about digital advertising, social media campaigns, and analytics. You'll help develop and implement marketing strategies.",
    requirements: [
      "Marketing, Business, or Communications student",
      "Strong writing and communication skills",
      "Basic understanding of social media platforms",
      "Creativity and attention to detail"
    ],
    location: "Cairo, Egypt",
    startDate: "2025-06-15",
    endDate: "2025-09-15",
    durationMonths: 3,
    paid: false,
    salary: 0,
    skills: ["Marketing", "Social Media", "Analytics", "Content Creation"],
    industry: "Marketing",
    isApproved: true,
    applicationsCount: 10,
    isRemote: true,
    department: "Marketing",
    contactPerson: "Nour Ahmed",
    tags: ["Marketing", "Social Media", "Analytics", "Content"],
    createdAt: "2025-02-01T10:30:00Z"
  },
  {
    id: 6,
    title: "Cybersecurity Intern",
    company: {
      id: 105,
      companyName: "SecureNet Solutions",
      logo: "https://placehold.co/100x100?text=SN",
      location: "Cairo, Egypt",
      industry: "Security"
    },
    description: "Work with our security team to identify vulnerabilities and implement security measures. You'll learn about penetration testing, security audits, and best practices.",
    requirements: [
      "Computer Science, Cybersecurity, or related field",
      "Basic knowledge of networking and security principles",
      "Familiarity with Linux operating systems",
      "Strong ethical standards"
    ],
    location: "Cairo, Egypt",
    startDate: "2025-07-01",
    endDate: "2025-09-30",
    durationMonths: 3,
    paid: true,
    salary: 4000,
    skills: ["Networking", "Linux", "Penetration Testing", "Security Audits"],
    industry: "Security",
    isApproved: false,
    applicationsCount: 0,
    isRemote: false,
    department: "Security",
    contactPerson: "Khaled Omar",
    tags: ["Cybersecurity", "Network Security", "Ethical Hacking", "IT"],
    createdAt: "2025-02-05T09:00:00Z"
  },
  {
    id: 7,
    title: "Product Management Intern",
    company: {
      id: 106,
      companyName: "InnovatePro",
      logo: "https://placehold.co/100x100?text=IP",
      location: "New Cairo, Egypt",
      industry: "Product"
    },
    description: "Join our product team to learn about the product development lifecycle. You'll assist in market research, feature planning, and user feedback analysis.",
    requirements: [
      "Business, Engineering, or related field",
      "Strong analytical skills",
      "Excellent communication abilities",
      "Interest in technology products"
    ],
    location: "New Cairo, Egypt",
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    durationMonths: 3,
    paid: true,
    salary: 3500,
    skills: ["Market Research", "Feature Planning", "User Feedback", "Analytics"],
    industry: "Product",
    isApproved: true,
    applicationsCount: 5,
    isRemote: false,
    department: "Product",
    contactPerson: "Yasmin Fawzy",
    tags: ["Product Management", "Strategy", "User Research", "Innovation"],
    createdAt: "2025-02-10T13:20:00Z"
  },
  {
    id: 8,
    title: "Cloud Engineering Intern",
    company: {
      id: 107,
      companyName: "CloudWave Technologies",
      logo: "https://placehold.co/100x100?text=CW",
      location: "Smart Village, Egypt"
    },
    description: "Gain experience with cloud infrastructure and DevOps practices. You'll work with AWS, Docker, and Kubernetes to deploy and manage applications.",
    requirements: [
      "Computer Science or related technical field",
      "Basic understanding of cloud concepts",
      "Familiarity with Linux command line",
      "Interest in infrastructure and automation"
    ],
    location: "Smart Village, Egypt",
    startDate: "2025-06-15",
    endDate: "2025-09-15",
    durationMonths: 3,
    paid: true,
    salary: 4000,
    skills: ["Cloud", "DevOps", "AWS", "Infrastructure"],
    industry: "Technology",
    isApproved: true,
    applicationsCount: 7,
    isRemote: false,
    department: "Cloud Infrastructure",
    contactPerson: "Adel Ibrahim",
    tags: ["Cloud", "DevOps", "AWS", "Infrastructure"],
    createdAt: "2025-02-15T10:45:00Z"
  },
  {
    id: 9,
    title: "Artificial Intelligence Research Intern",
    company: {
      id: 108,
      companyName: "AI Solutions",
      logo: "https://placehold.co/100x100?text=AI",
      location: "Alexandria, Egypt"
    },
    description: "Participate in cutting-edge AI research projects. You'll help develop and test machine learning models for various applications.",
    requirements: [
      "Computer Science, Math, or related field",
      "Strong programming skills (Python preferred)",
      "Knowledge of machine learning concepts",
      "Experience with deep learning frameworks is a plus"
    ],
    location: "Alexandria, Egypt",
    startDate: "2025-07-01",
    endDate: "2025-10-31",
    durationMonths: 4,
    paid: true,
    salary: 3500,
    skills: ["AI", "Machine Learning", "Research", "Deep Learning"],
    industry: "Technology",
    isApproved: false,
    applicationsCount: 0,
    isRemote: true,
    department: "Research",
    contactPerson: "Dina Kamel",
    tags: ["AI", "Machine Learning", "Research", "Deep Learning"],
    createdAt: "2025-02-20T09:15:00Z"
  },
  {
    id: 10,
    title: "Biomedical Engineering Intern",
    company: {
      id: 109,
      companyName: "HealthTech Innovations",
      logo: "https://placehold.co/100x100?text=HT",
      location: "Cairo, Egypt"
    },
    description: "Work on innovative medical devices and healthcare solutions. You'll collaborate with engineers and medical professionals on real-world health technology challenges.",
    requirements: [
      "Biomedical Engineering or related field",
      "Basic understanding of medical device principles",
      "CAD skills preferred",
      "Strong attention to detail and documentation"
    ],
    location: "Cairo, Egypt",
    startDate: "2025-06-15",
    endDate: "2025-09-15",
    durationMonths: 3,
    paid: true,
    salary: 3000,
    skills: ["Biomedical", "Healthcare", "Engineering", "Medical Devices"],
    industry: "Healthcare",
    isApproved: true,
    applicationsCount: 3,
    isRemote: false,
    department: "Engineering",
    contactPerson: "Hany Yousef",
    tags: ["Biomedical", "Healthcare", "Engineering", "Medical Devices"],
    createdAt: "2025-02-25T14:30:00Z"
  }
];